version: '3.8'

services:
  # MySQL 服务
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # 设置 root 用户的密码
      MYSQL_DATABASE: test          # 可选：初始化一个数据库
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # RabbitMQ 服务
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ 管理界面
    networks:
      - app-network

  # Redis 服务
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"  # Redis 默认端口
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
